---
title: "The UPR & Maternal Health"
params:
  country_name: "Switzerland"
  upr_all: NULL
  rec_plot: NULL
  mmr_map_plot: NULL
documentclass: article
# classoption: twocolumn
output: 
  pdf_document:
    includes:
      in_header: preamble-b.tex
    keep_tex: true
    latex_engine: xelatex
geometry: 
  - top=2cm
  - bottom=0.5cm
  - left=0.2cm
  - right=0.2cm
papersize: a4
date: "2025-09-30"
---
```{r setup, include=FALSE}
# This chunk loads the necessary packages for the report
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.align='center', out.width="100%")
pacman::p_load(
  ggplot2, 
  ggtext, 
  patchwork
)
```

\maketitle
# `r params$country_name`  

Some brief text here, for context, that runs the \textcolor{red}{entire width of the page}. Indicator results, tables, and figures can go into the columns below.

<!-- \textcolor{fgcolor}{\hlCeHDIBlue{colortest}} -->
<!-- \textcolor{fgcolor}{\textbf{\hlCeHDIBlue{colortest}}} -->
<!-- \textcolor{fgcolor}{\hlCeHDIRed{colortest}} -->
<!-- \textcolor{fgcolor}{\textbf{\hlCeHDIRed{colortest}}} -->

\redrule
```{=latex}
\begin{multicols*}{2}
```

This plot shows all health-related recommendations received by the selected state across all UPR cycles.
```{r, fig.width=6, fig.height=5.5}
print(params$upr_all+
        theme(
          axis.title.x = element_text(color = "black"),
          plot.background = element_rect(color = "#1c164d", fill = NA),
          panel.background = element_blank(),
          legend.background = element_blank()
        )
)
```

```{r, fig.width=4, fig.height=3.5}
print(
  params$rec_plot+
    labs(y="Recommendations (N)")+
    geom_text(aes(label = sprintf("%1.0f", n_tot), y = n_tot, vjust = -0.2), size = 5, fontface = "bold", color = "#1c164d") +
    theme(
      panel.grid = element_blank(),
      axis.text.x = element_text(size = 12, color = "#1c164d"),
      axis.text.y = element_text(size = 12, color = "#1c164d"),
      axis.title.x = element_blank(),
      axis.title.y = element_text(size = 14, color = "#1c164d"),
      legend.position = "bottom",
      # legend.position = c(0.01, 0.99),
      # legend.justification = c("left", "top"),
      legend.text = element_text(size = 12,colour = "#1c164d"),
      # plot.background = element_blank(),
      plot.background = element_rect(color = "#1c164d", fill = NA),
      panel.border = element_rect(color = "#1c164d"),
      # panel.border = element_blank(),
      axis.ticks = element_line(color = "#1c164d"),
      panel.background = element_blank(),
      legend.background = element_blank(),
      strip.background = element_blank(),
      strip.text = element_blank(),
      plot.title = element_blank()
    )
)
```

```{r,fig.height=7, out.height= 5 }
print(
  params$mmr_map_plot+theme(
    plot.background = element_blank()
  )&
    plot_annotation(theme = theme(
      plot.background = element_rect(color = "#1c164d", fill=NA)
      )
      )
)
```


<!-- ```{r, fig.height=3, out.width="80%"} -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_violin() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_boxplot() -->
<!-- ``` -->

<!-- ```{r, fig.height=3, out.width="80%"} -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_violin() -->
<!-- ``` -->

<!-- ```{r, fig.width=3, out.height="500pt", } -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_boxplot() -->
<!-- ``` -->

<!-- ```{r, fig.height=3, out.width="80%"} -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_violin() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_boxplot() -->
<!-- ``` -->

<!-- ```{r, fig.height=3, out.width="80%"} -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_violin() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- penguins |> ggplot(aes(x = island, y = bill_len, fill=species))+geom_boxplot() -->
<!-- ``` -->

```{=latex}
\end{multicols*}
```