theme_labels <- tribble(
  ~"variable", ~"theme_label",
  "health_related", "Health-related",
  "health_systems", "Health systems and services",
  "emergencies", "Health security, emergencies, and disaster relief",
  "ncd", "Non-communicable diseases",
  "communicable", "Communicable diseases",
  "SRHR", "Sexual and reproductive health and rights",
  "mental_health", "Mental health",
  "SOCED", "Social and economic determinants of health",
  "GBV", "Gender-based violence and harmful practices",
  "women", "Women's health",
  "MCAH", "Child and adolescent health",
  "maternal_health", "Maternal health",
  "abortion", "Abortion",
  "contraception", "Family planning",
  "essential_medicines", "Essential medicines and health products",
  "disabilities", "Disabilities and health",
  "LGBTI", "Health of LGBTI persons",
  "HIV", "HIV/AIDS and STIs",
  "TB_malaria", "TB and malaria",
  "NTD", "Neglected tropical diseases",
  "TB_malaria_NTD", "TB, malaria, and neglected tropical diseases",
  "vaccinations", "Immunization, vaccines, and pharmaceutical products",
  "WASH", "Water and sanitation",
  "nutrition", "Nutrition",
  "incarcerated", "Health of incarcerated persons",
  "occupational_health", "Occupational health",
  "migrant_health", "Refugee and migrant health",
  "other_health_related", "Other health-related"
)
