theme_labels <- tribble(
  ~"variable", ~"theme_label",
  "health_related", "Health-related",
  "health_systems", "Health systems and services",
  # "emergencies", "Health security, emergencies, and disaster relief",
  "emergencies", "Health emergencies",
  "ncd", "Non-communicable diseases",
  "communicable", "Communicable diseases",
  "SRHR", "Other SRHR (sexual health/wellbeing/education)",
  "sexual_health", "Sexual health and wellbeing",
  "sexual_education", "Sexual education",
  "mental_health", "Mental health",
  "SOCED", "Social and economic determinants of health",
  # "GBV", "Gender-based violence and harmful practices",
  "GBV", "GBV and harmful practices",
  "women", "Women's health",
  "CAH", "Child and adolescent health",
  "maternal_health", "Maternal health",
  "abortion", "Abortion",
  "contraception", "Family planning",
  "essential_medicines", "Essential medicines and health products",
  "disabilities", "Disabilities and health",
  "LGBTI", "Health of LGBTQI persons",
  "HIV", "HIV/AIDS and STIs",
  "TB_malaria", "TB and malaria",
  "NTD", "Neglected tropical diseases",
  # "TB_malaria_NTD", "TB, malaria, and neglected tropical diseases",
  "TB_malaria_NTD", "TB, malaria, and NTDs",
  "vaccinations", "Vaccines, pharmaceuticals, and health products",
  "WASH", "Water and sanitation",
  "nutrition", "Nutrition",
  "incarcerated", "Health of incarcerated persons",
  "occupational_health", "Occupational health",
  "migrant_health", "Refugee and migrant health",
  "SRHR_any", "SRHR (combined)",
  "health_services", "Health services (combined)",
  "Communicable_combined", "Communicable diseases (combined)",
  "maternal_no_abortion", "Maternal Health",
  "abortion_maternal", "Abortion (maternal health context)",
  "other_health_related", "Other health-related"
)
