theme_labels <- tribble(
  ~"variable", ~"theme_label", ~"theme_label_fr",
  "health_related", "Health-related", "Lié à la santé",
  "health_systems", "Health systems and services", "Systèmes et services de santé",
  # "emergencies", "Health security, emergencies, and disaster relief", "Sécurité sanitaire, urgences et secours en cas de catastrophe",
  "emergencies", "Health emergencies", "Urgences sanitaires",
  "ncd", "Non-communicable diseases", "Maladies non transmissibles",
  "communicable", "Communicable diseases", "Maladies transmissibles",
  "SRHR", "Other SRHR (sexual health/wellbeing/education)", "Autre SDSR (santé/bien-être/éducation sexuels)",
  "sexual_health", "Sexual health and wellbeing", "Santé et bien-être sexuels",
  "sexual_education", "Sexual education", "Éducation sexuelle",
  "mental_health", "Mental health", "Santé mentale",
  "SOCED", "Social and economic determinants of health", "Déterminants sociaux et économiques de la santé",
  # "GBV", "Gender-based violence and harmful practices", "Violences basées sur le genre et pratiques préjudiciables",
  "GBV", "GBV and harmful practices", "VBG et pratiques préjudiciables",
  "women", "Women's health", "Santé des femmes",
  "CAH", "Child and adolescent health", "Santé de l'enfant et de l'adolescent",
  "maternal_health", "Maternal health", "Santé maternelle",
  "abortion", "Abortion", "Avortement",
  "contraception", "Family planning", "Planification familiale",
  "essential_medicines", "Essential medicines and health products", "Médicaments essentiels et produits de santé",
  "disabilities", "Disabilities and health", "Handicap et santé",
  "LGBTI", "Health of LGBTQI persons", "Santé des personnes LGBTQI",
  "HIV", "HIV/AIDS and STIs", "VIH/sida et IST",
  "TB_malaria", "TB and malaria", "Tuberculose et paludisme",
  "NTD", "Neglected tropical diseases", "Maladies tropicales négligées",
  # "TB_malaria_NTD", "TB, malaria, and neglected tropical diseases", "Tuberculose, paludisme et maladies tropicales négligées",
  "TB_malaria_NTD", "TB, malaria, and NTDs", "Tuberculose, paludisme et MTN",
  "vaccinations", "Vaccines, pharmaceuticals, and health products", "Vaccins, produits pharmaceutiques et produits de santé",
  "WASH", "Water and sanitation", "Eau et assainissement",
  "nutrition", "Nutrition", "Nutrition",
  "incarcerated", "Health of incarcerated persons", "Santé des personnes incarcérées",
  "occupational_health", "Occupational health", "Santé au travail",
  "migrant_health", "Refugee and migrant health", "Santé des réfugiés et des migrants",
  "SRHR_any", "SRHR (combined)", "SDSR (combiné)",
  "health_services", "Health services (combined)", "Services de santé (combinés)",
  "Communicable_combined", "Communicable diseases (combined)", "Maladies transmissibles (combinées)",
  "maternal_no_abortion", "Maternal Health", "Santé maternelle",
  "abortion_maternal", "Abortion (maternal health context)", "Avortement (contexte de santé maternelle)",
  "other_health_related", "Other health-related", "Autre lié à la santé"
)
