# Extract UPR recommendations from a draft report into a tidy data frame.
#
# v4 -- works directly on the ORIGINAL, unedited Working Group draft report.
#       No manual pre-processing of the .docx is needed any more.
#
# What's new relative to extract_recs.R (v3):
#
#   1. Section scoping. The script locates the "Conclusions and/or
#      recommendations" heading and the closing disclaimer paragraph
#      ("All conclusions and/or recommendations contained in the present
#      report reflect the position ...") / "Annex" heading, and only looks
#      for recommendations between the two. If no such heading exists
#      (e.g. a file that was already trimmed by hand), it falls back to
#      scanning the whole document, like v3 did.
#
#   2. Position column. Inside the section, literal-numbered lead-in
#      paragraphs ("6.", "7.", "8.", ...) announce each block of
#      recommendations:
#        "... enjoy the support of X:"        -> Supported
#        "... have been noted by X:"          -> Noted
#        "... will be examined by X, which
#         will provide responses in due time" -> Under consideration
#      Every recommendation inherits the position of the nearest preceding
#      lead-in. If a document contains ONLY "will be examined" lead-in(s)
#      (i.e. the State under review has not yet responded to anything, as
#      in the Mozambique draft), position is NA for all rows;
#      "Under consideration" is only used when it appears alongside
#      Supported/Noted blocks (as in the Somalia draft).
#
#   3. Paragraph labels per block. In auto-numbered documents the labels
#      are now "<lead-in number>.<n within block>" (numbering restarts at
#      each lead-in, per UN convention), instead of a single global
#      counter. Documents with one block are unaffected.
#
# Everything else -- the two supported numbering formats, the rec-shape
# detection, the state parser and the sanity warnings -- is carried over
# from v3:
#
#   A. Auto-numbered (e.g. Mozambique/WG52). Every recommendation
#      paragraph sits in a Word numbered list; the "6.1, 6.2, ..." labels
#      are generated by Word from the list definition and never appear as
#      literal text.
#
#   B. Literal-prefix (e.g. Somalia/WG52, Niger/WG52). The paragraphs are
#      NOT in a Word numbered list. Instead each paragraph BEGINS with its
#      own number as plain text -- e.g. "6.1\tRatify the Second Optional
#      Protocol...".
#
# Detection: a paragraph is "rec-shaped" if it ends with "(State); ...".
# If most rec-shaped paragraphs start with "N.M" plain-text prefixes,
# that's format B. Otherwise format A.
#
# Tested on Mozambique (auto-numbered original, 292 recs, no positions)
# and Somalia (literal-prefix original, 288 recs: 259 Supported /
# 3 Under consideration / 26 Noted).

suppressPackageStartupMessages({
  library(xml2)
  library(stringr)
  library(tibble)
  library(dplyr)
  library(here)
})

# Patterns
.STATE_RE   <- "\\([^()]*(?:\\([^()]*\\)[^()]*)*\\)"
.TRAIL_RE   <- paste0("(", .STATE_RE, "(?:\\s*;\\s*", .STATE_RE, ")*)\\s*;?\\s*$")
.PREFIX_RE  <- "^\\s*(\\d+)\\.(\\d+)\\s*"
.LEADIN_RE  <- "^\\s*(\\d+)\\.(?!\\d)"   # top-level "6." (but not "6.1")
.SECTION_RE <- "^\\s*(?:[IVXLC]+\\.)?\\s*Conclusions?\\s+and/?or\\s+recommendations\\s*$"
.END_RE     <- "All conclusions and/or recommendations contained in the present report"
.ANNEX_RE   <- "^\\s*Annexe?s?\\s*$"
.MODE_THRESHOLD <- 0.8   # >= 80% to commit to a format

.POSITION_LEVELS <- c("Supported", "Noted", "Under consideration")

`%||%` <- function(a, b) if (is.null(a) || is.na(a)) b else a

# ---- Recommendation parser --------------------------------------------------
# Splits "rec text (State); (State); ..." into rec text + state list.
# Caller is responsible for stripping any leading "6.N\t" prefix beforehand.

parse_recommendation <- function(x) {
  x <- str_replace(x, "[;.\\s]+$", "")
  m <- str_match(x, .TRAIL_RE)
  if (is.na(m[1, 1])) return(list(text = x, states = NA_character_))
  trailing <- m[1, 2]
  rec_text <- str_trim(str_sub(x, 1L, str_length(x) - str_length(trailing)))
  states   <- str_extract_all(trailing, .STATE_RE)[[1]]
  states   <- str_trim(str_sub(states, 2L, -2L))
  list(text = rec_text, states = paste(states, collapse = "; "))
}

# ---- Lead-in classifier -----------------------------------------------------
# Maps a lead-in paragraph ("6.The recommendations ... enjoy the support of
# X:") to a position. Order matters: the Supported and Noted lead-ins both
# also contain "have been examined", so "will be examined" (future tense)
# must be checked last.

classify_leadin <- function(text) {
  case_when(
    str_detect(text, regex("enjoys?\\s+the\\s+support", ignore_case = TRUE))   ~ "Supported",
    str_detect(text, regex("(have\\s+been|are)\\s+noted", ignore_case = TRUE)) ~ "Noted",
    str_detect(text, regex("will\\s+be\\s+examined", ignore_case = TRUE))      ~ "Under consideration",
    .default = NA_character_
  )
}

# ---- Main extractor ---------------------------------------------------------
#
# Args:
#   docx_path       : path to the .docx (original, unedited draft report)
#   mode            : "auto" (default) / "auto-numbered" / "literal-prefix"
#   num_id          : in auto-numbered mode, optional override (else detected)
#   section_prefix  : fallback for the "6" in "6.1, 6.2, ..." when a block
#                     has no literal lead-in number -- defaults to "6"
#   verbose         : print summary + warnings
#
# Returns: tibble with paragraph, recommendation, states, position.

extract_upr_recommendations <- function(
    docx_path,
    mode           = c("auto", "auto-numbered", "literal-prefix"),
    num_id         = NULL,
    section_prefix = NULL,
    verbose        = TRUE
) {
  mode <- match.arg(mode)
  stopifnot(file.exists(docx_path))

  # 1. Read document.xml straight out of the .docx zip. (A unz() connection
  #    rather than utils::unzip(): no temp files, and it copes with archives
  #    that crash R's unzip-to-disk path.)
  doc <- read_xml(unz(docx_path, "word/document.xml"))
  ns  <- xml_ns(doc)

  # 2. Walk every <w:p>, recording numId + concatenated text.
  paras <- xml_find_all(doc, ".//w:p", ns = ns)
  para_df <- tibble(
    idx  = seq_along(paras),
    nid  = vapply(paras, function(p) {
      ids <- xml_find_all(p, ".//w:numId", ns = ns)
      if (length(ids) == 0L) NA_character_ else xml_attr(ids[[1L]], "val")
    }, character(1)),
    text = vapply(paras, function(p) {
      str_trim(paste(xml_text(xml_find_all(p, ".//w:t", ns = ns)),
                     collapse = ""))
    }, character(1))
  ) |>
    filter(nzchar(text))

  # 3. Scope to the "Conclusions and/or recommendations" section.
  sec_start <- which(str_detect(para_df$text,
                                regex(.SECTION_RE, ignore_case = TRUE)))
  if (length(sec_start) > 0L) {
    sec_start <- sec_start[1L]
    after     <- seq(sec_start + 1L, nrow(para_df))
    sec_end   <- after[str_detect(para_df$text[after],
                                  regex(.END_RE, ignore_case = TRUE)) |
                         str_detect(para_df$text[after], .ANNEX_RE)]
    sec_end   <- if (length(sec_end) > 0L) sec_end[1L] else nrow(para_df) + 1L
    if (verbose) {
      cat(sprintf(
        "Recommendations section: '%s' (doc-paragraph idx=%d to %s)\n",
        str_trunc(para_df$text[sec_start], 60), para_df$idx[sec_start],
        if (sec_end <= nrow(para_df))
          sprintf("idx=%d '%s'", para_df$idx[sec_end],
                  str_trunc(para_df$text[sec_end], 50))
        else "end of document"))
    }
    para_df <- para_df[seq(sec_start + 1L, sec_end - 1L), ]
  } else if (verbose) {
    cat("WARNING: no 'Conclusions and/or recommendations' heading found; ",
        "scanning the whole document.\n", sep = "")
  }

  para_df <- para_df |>
    mutate(
      text_clean = str_replace(text, "[;.\\s]+$", ""),
      is_rec     = str_detect(text_clean, .TRAIL_RE),
      pre_match  = str_match(text, .PREFIX_RE)[, 1L],
      has_prefix = !is.na(pre_match)
    )

  # 4. Position blocks. A lead-in is a non-rec paragraph starting with a
  #    literal top-level number ("6." but not "6.1"). block 0 = anything
  #    before the first lead-in.
  para_df <- para_df |>
    mutate(
      is_leadin  = !is_rec & str_detect(text, .LEADIN_RE),
      leadin_num = if_else(is_leadin, str_match(text, .LEADIN_RE)[, 2L],
                           NA_character_),
      block      = cumsum(is_leadin)
    )

  blocks <- para_df |>
    filter(is_leadin) |>
    transmute(
      block,
      block_prefix   = leadin_num,
      block_position = classify_leadin(text),
      leadin_text    = text
    )

  # NA rule: "Under consideration" only counts as a position when the State
  # has actually responded to something (i.e. there is also a Supported or
  # Noted block). A document whose only lead-in(s) say "will be examined"
  # has no positions yet -> all NA.
  has_response <- any(blocks$block_position %in% c("Supported", "Noted"))
  if (!has_response) blocks$block_position <- NA_character_

  if (verbose && nrow(blocks) > 0L) {
    cat("Lead-in paragraphs found:\n")
    for (i in seq_len(nrow(blocks))) {
      cat(sprintf("  [%s.] %s -> %s\n",
                  blocks$block_prefix[i],
                  str_trunc(blocks$leadin_text[i], 90),
                  blocks$block_position[i] %||% if (has_response)
                    "<unrecognized>" else "NA (no positions given yet)"))
    }
  }

  para_df <- para_df |>
    left_join(select(blocks, block, block_prefix, block_position),
              by = "block")

  # Recs sitting under an unrecognized lead-in deserve a loud warning
  # (an unrecognized lead-in with no recs after it is fine -- e.g. a
  # free-text "X notes the relevant recommendations as follows: ..."
  # paragraph just before the closing disclaimer).
  if (verbose && has_response) {
    orphaned <- para_df |>
      filter(is_rec, block > 0L, is.na(block_position))
    if (nrow(orphaned) > 0L) {
      bad_blocks <- blocks |> filter(block %in% unique(orphaned$block))
      cat(sprintf(
        "\nWARNING: %d recommendation(s) follow lead-in(s) whose position ",
        nrow(orphaned)))
      cat("could not be classified; their position is NA:\n")
      for (i in seq_len(nrow(bad_blocks))) {
        cat(sprintf("  [%s.] %s\n", bad_blocks$block_prefix[i],
                    str_trunc(bad_blocks$leadin_text[i], 120)))
      }
    }
  }

  # 5. Mode detection
  rec_paras <- filter(para_df, is_rec)
  if (nrow(rec_paras) == 0L) {
    stop("No paragraphs match the recommendation shape '... (State);'. ",
         "If this is a chronological-list-style draft (one rec per ",
         "speaker block), use extract_chrono_recommendations() instead.")
  }

  if (mode == "auto") {
    prefix_frac <- mean(rec_paras$has_prefix)
    nid_frac    <- mean(!is.na(rec_paras$nid))
    if (prefix_frac >= .MODE_THRESHOLD && nid_frac < .MODE_THRESHOLD) {
      mode <- "literal-prefix"
    } else {
      mode <- "auto-numbered"
    }
    if (verbose) {
      cat(sprintf(
        "Detected format: %s (prefix coverage %.0f%%, numId coverage %.0f%%)\n",
        mode, 100 * prefix_frac, 100 * nid_frac))
    }
  }

  # 6. Dispatch
  out <- switch(mode,
                "literal-prefix" = .extract_literal_prefix(para_df, rec_paras,
                                                           section_prefix, verbose),
                "auto-numbered"  = .extract_auto_numbered(para_df, num_id,
                                                          section_prefix %||% "6", verbose)
  )
  out <- mutate(out, position = factor(position, levels = .POSITION_LEVELS))

  if (verbose) {
    n_pairs <- sum(str_count(out$states, ";"), na.rm = TRUE) + sum(!is.na(out$states))
    cat(sprintf("\nExtracted %d recommendations (%d rec-state pairs).\n",
                nrow(out), n_pairs))
    pos_counts <- table(out$position, useNA = "ifany")
    pos_names  <- names(pos_counts)
    pos_names[is.na(pos_names)] <- "NA"
    cat("Positions: ",
        paste(sprintf("%s = %d", pos_names, pos_counts), collapse = ", "),
        "\n", sep = "")
  }
  out
}

# ---- Format A: auto-numbered (Mozambique-style) -----------------------------
# Paragraph labels restart at each lead-in block: "<lead-in number>.<n>".

.extract_auto_numbered <- function(para_df, num_id, section_prefix, verbose) {
  if (is.null(num_id)) {
    rec_in_lists <- para_df |> filter(is_rec, !is.na(nid))
    if (nrow(rec_in_lists) == 0L) {
      stop("auto-numbered mode forced, but no rec-shaped paragraphs are in ",
           "any numbered list. Try mode = \"literal-prefix\".")
    }
    nid_counts <- sort(table(rec_in_lists$nid), decreasing = TRUE)
    num_id <- names(nid_counts)[1L]
    if (verbose) {
      cat(sprintf("Auto-detected numId='%s' (%d rec-shaped paragraphs)\n",
                  num_id, nid_counts[[1L]]))
      if (length(nid_counts) > 1L) {
        runners <- paste(sprintf("%s (%d)", names(nid_counts)[-1L],
                                 as.integer(nid_counts)[-1L]),
                         collapse = ", ")
        cat(sprintf("Other numIds with rec-shaped paragraphs: %s\n", runners))
      }
    }
  }

  numbered <- para_df |> filter(is_rec, !is.na(nid), nid == num_id) |>
    arrange(idx) |>
    group_by(block) |>
    mutate(paragraph = sprintf("%s.%d", coalesce(block_prefix, section_prefix),
                               row_number())) |>
    ungroup()
  unnumbered <- para_df |> filter(is_rec, is.na(nid) | nid != num_id) |>
    arrange(idx) |>
    mutate(paragraph = sprintf("%s.U%d", section_prefix, row_number()))

  if (verbose && nrow(unnumbered) > 0L) {
    cat(sprintf(
      "\nWARNING: %d rec-shaped paragraph(s) NOT in numId='%s'. ",
      nrow(unnumbered), num_id))
    cat(sprintf("Labelled %s.U1..%s.U%d:\n",
                section_prefix, section_prefix, nrow(unnumbered)))
    for (i in seq_len(nrow(unnumbered))) {
      cat(sprintf("  [%s | doc-paragraph idx=%d, numId=%s]\n",
                  unnumbered$paragraph[i], unnumbered$idx[i],
                  unnumbered$nid[i] %||% "<none>"))
      cat(sprintf("    %s\n", str_trunc(unnumbered$text[i], 160)))
    }
  }
  in_list_not_rec <- para_df |> filter(!is.na(nid), nid == num_id, !is_rec)
  if (verbose && nrow(in_list_not_rec) > 0L) {
    cat(sprintf(
      "\nWARNING: %d paragraph(s) in numId='%s' do NOT match rec shape:\n",
      nrow(in_list_not_rec), num_id))
    for (i in seq_len(nrow(in_list_not_rec))) {
      cat(sprintf("  [doc-paragraph idx=%d]: %s\n",
                  in_list_not_rec$idx[i],
                  str_trunc(in_list_not_rec$text[i], 160)))
    }
  }

  combined <- bind_rows(numbered, unnumbered) |> arrange(idx)
  parsed   <- lapply(combined$text, parse_recommendation)
  tibble(
    paragraph      = combined$paragraph,
    recommendation = vapply(parsed, `[[`, character(1), "text"),
    states         = vapply(parsed, `[[`, character(1), "states"),
    position       = combined$block_position
  )
}

# ---- Format B: literal-prefix (Somalia/Niger-style) --------------------------

.extract_literal_prefix <- function(para_df, rec_paras,
                                    section_prefix, verbose) {
  prefixed <- rec_paras |> filter(has_prefix) |>
    mutate(
      sec = str_match(text, .PREFIX_RE)[, 2L],
      num = as.integer(str_match(text, .PREFIX_RE)[, 3L]),
      # Recommendation text with the "X.Y\t" prefix stripped:
      body = str_trim(str_replace(text, .PREFIX_RE, ""))
    ) |>
    arrange(idx)

  if (is.null(section_prefix)) {
    section_prefix <- names(sort(table(prefixed$sec), decreasing = TRUE))[1L]
    if (verbose && dplyr::n_distinct(prefixed$sec) > 1L) {
      cat(sprintf(
        "Note: literal prefixes use %d different section numbers (%s), ",
        dplyr::n_distinct(prefixed$sec),
        paste(unique(prefixed$sec), collapse = ", ")))
      cat("as expected when recommendations are grouped by position.\n")
    }
  }

  # Sanity checks on the literal numbering (within each section number,
  # since numbering restarts at each lead-in block)
  if (verbose) {
    for (s in unique(prefixed$sec)) {
      nums      <- sort(prefixed$num[prefixed$sec == s])
      expected  <- seq_len(max(nums))
      gaps      <- setdiff(expected, nums)
      dup_count <- sum(duplicated(nums))
      cat(sprintf("Literal prefixes span %s.%d to %s.%d (%d paragraphs).\n",
                  s, min(nums), s, max(nums), length(nums)))
      if (length(gaps) > 0L) {
        cat(sprintf("WARNING: %d gap(s) in %s.N numbering: %s%s\n",
                    length(gaps), s,
                    paste(head(gaps, 10), collapse = ", "),
                    if (length(gaps) > 10L) ", ..." else ""))
      }
      if (dup_count > 0L) {
        cat(sprintf("WARNING: %d duplicate paragraph number(s) in %s.N.\n",
                    dup_count, s))
      }
    }
  }

  # Anything rec-shaped without a literal prefix? (shouldn't happen, but
  # worth flagging if it does)
  unprefixed <- rec_paras |> filter(!has_prefix)
  if (verbose && nrow(unprefixed) > 0L) {
    cat(sprintf(
      "\nWARNING: %d rec-shaped paragraph(s) lack a literal '%s.N' prefix:\n",
      nrow(unprefixed), section_prefix))
    for (i in seq_len(nrow(unprefixed))) {
      cat(sprintf("  [doc-paragraph idx=%d]: %s\n",
                  unprefixed$idx[i],
                  str_trunc(unprefixed$text[i], 160)))
    }
  }

  parsed <- lapply(prefixed$body, parse_recommendation)
  tibble(
    paragraph      = sprintf("%s.%d", prefixed$sec, prefixed$num),
    recommendation = vapply(parsed, `[[`, character(1), "text"),
    states         = vapply(parsed, `[[`, character(1), "states"),
    position       = prefixed$block_position
  )
}

# ---- Run --------------------------------------------------------------------

if (sys.nframe() == 0) {
  targets <- c(
    # Mozambique = "Mozambique - Draft report circulated on 7 May 2026_original.docx",
    Somalia    = "Somalia - Draft report circulated on 12 May 2026_original.docx"
  )
  for (state in names(targets)) {
    path <- here("data", "UPR_WG_docs", targets[[state]])
    if (!file.exists(path)) next
    cat("\n----", targets[[state]], "----\n")
    recs <- extract_upr_recommendations(path)
    print(head(recs, 3))
    print(tail(recs, 3))
    saveRDS(recs, here("data", "UPR_WG_docs",
                       paste0(state, "_upr_recommendations.rds")))
  }
}