# Extract UPR recommendations from a draft report into a tidy data frame.
#
# v3 -- handles two different draft formats automatically:
#
#   A. Auto-numbered (e.g. Namibia/WG52). Every recommendation paragraph
#      sits in a Word numbered list; the "6.1, 6.2, ..." labels are
#      generated by Word from the list definition and never appear as
#      literal text. This was v1/v2's only supported format.
#
#   B. Literal-prefix (e.g. Niger/WG52). The paragraphs are NOT in a
#      Word numbered list at all. Instead each paragraph BEGINS with
#      its own number as plain text -- e.g. "6.1\tRatify the Second
#      Optional Protocol...". v2 errored out on these with
#      "No paragraphs match the recommendation shape".
#
# Detection: a paragraph is "rec-shaped" if it ends with "(State); ...".
# If most rec-shaped paragraphs start with "N.M" plain-text prefixes,
# that's format B. Otherwise format A. The thresholds (0.8) leave room
# for the kind of one-off authoring inconsistency v2 already handled.
#
# Bug fixes carried forward from v2:
#   - "(2025) (Ireland)" no longer treats (2025) as a state
#     (states must be ;-separated)
#   - paragraphs that are rec-shaped but missing from the dominant numId
#     are still captured (labelled .U1, .U2, ...) instead of silently dropped
#
# Tested on Namibia (auto-numbered, 290 recs) and Niger (literal-prefix,
# 265 recs). Last paragraph of the Niger file ends with "(France)." rather
# than ";"; the trailing-cleanup pass handles that.

suppressPackageStartupMessages({
  library(xml2)
  library(stringr)
  library(tibble)
  library(dplyr)
  library(here)
})

# Patterns
.STATE_RE  <- "\\([^()]*(?:\\([^()]*\\)[^()]*)*\\)"
.TRAIL_RE  <- paste0("(", .STATE_RE, "(?:\\s*;\\s*", .STATE_RE, ")*)\\s*;?\\s*$")
.PREFIX_RE <- "^\\s*(\\d+)\\.(\\d+)\\s*"
.MODE_THRESHOLD <- 0.8   # >= 80% to commit to a format

`%||%` <- function(a, b) if (is.null(a) || is.na(a)) b else a

# ---- Recommendation parser --------------------------------------------------
# Splits "rec text (State); (State); ..." into rec text + state list.
# Caller is responsible for stripping any leading "6.N\t" prefix beforehand.

parse_recommendation <- function(x) {
  x <- str_replace(x, "[;.\\s]+$", "")
  m <- str_match(x, .TRAIL_RE)
  if (is.na(m[1, 1])) return(list(text = x, states = NA_character_))
  trailing <- m[1, 2]
  rec_text <- str_trim(str_sub(x, 1L, str_length(x) - str_length(trailing)))
  states   <- str_extract_all(trailing, .STATE_RE)[[1]]
  states   <- str_trim(str_sub(states, 2L, -2L))
  list(text = rec_text, states = paste(states, collapse = "; "))
}

# ---- Main extractor ---------------------------------------------------------
#
# Args:
#   docx_path       : path to the .docx
#   mode            : "auto" (default) / "auto-numbered" / "literal-prefix"
#   num_id          : in auto-numbered mode, optional override (else detected)
#   section_prefix  : the "6" in "6.1, 6.2, ..." -- detected when possible,
#                     else defaults to "6"
#   verbose         : print summary + warnings
#
# Returns: tibble with paragraph, recommendation, states.

extract_upr_recommendations <- function(
    docx_path,
    mode           = c("auto", "auto-numbered", "literal-prefix"),
    num_id         = NULL,
    section_prefix = NULL,
    verbose        = TRUE
) {
  mode <- match.arg(mode)
  stopifnot(file.exists(docx_path))
  
  # 1. Unzip and read document.xml
  tmp <- tempfile(); dir.create(tmp); on.exit(unlink(tmp, recursive = TRUE))
  utils::unzip(docx_path, exdir = tmp)
  doc <- read_xml(file.path(tmp, "word", "document.xml"))
  ns  <- xml_ns(doc)
  
  # 2. Walk every <w:p>, recording numId + concatenated text.
  paras <- xml_find_all(doc, ".//w:p", ns = ns)
  para_df <- tibble(
    idx  = seq_along(paras),
    nid  = vapply(paras, function(p) {
      ids <- xml_find_all(p, ".//w:numId", ns = ns)
      if (length(ids) == 0L) NA_character_ else xml_attr(ids[[1L]], "val")
    }, character(1)),
    text = vapply(paras, function(p) {
      str_trim(paste(xml_text(xml_find_all(p, ".//w:t", ns = ns)),
                     collapse = ""))
    }, character(1))
  ) |>
    filter(nzchar(text)) |>
    mutate(
      text_clean = str_replace(text, "[;.\\s]+$", ""),
      is_rec     = str_detect(text_clean, .TRAIL_RE),
      pre_match  = str_match(text, .PREFIX_RE)[, 1L],
      has_prefix = !is.na(pre_match)
    )
  
  # 3. Mode detection
  rec_paras <- filter(para_df, is_rec)
  if (nrow(rec_paras) == 0L) {
    stop("No paragraphs match the recommendation shape '... (State);'. ",
         "If this is a chronological-list-style draft (one rec per ",
         "speaker block), use extract_chrono_recommendations() instead.")
  }
  
  if (mode == "auto") {
    prefix_frac <- mean(rec_paras$has_prefix)
    nid_frac    <- mean(!is.na(rec_paras$nid))
    if (prefix_frac >= .MODE_THRESHOLD && nid_frac < .MODE_THRESHOLD) {
      mode <- "literal-prefix"
    } else {
      mode <- "auto-numbered"
    }
    if (verbose) {
      cat(sprintf(
        "Detected format: %s (prefix coverage %.0f%%, numId coverage %.0f%%)\n",
        mode, 100 * prefix_frac, 100 * nid_frac))
    }
  }
  
  # 4. Dispatch
  out <- switch(mode,
                "literal-prefix" = .extract_literal_prefix(para_df, rec_paras,
                                                           section_prefix, verbose),
                "auto-numbered"  = .extract_auto_numbered(para_df, num_id,
                                                          section_prefix %||% "6", verbose)
  )
  
  if (verbose) {
    n_pairs <- sum(str_count(out$states, ";"), na.rm = TRUE) + sum(!is.na(out$states))
    cat(sprintf("\nExtracted %d recommendations (%d rec-state pairs).\n",
                nrow(out), n_pairs))
  }
  out
}

# ---- Format A: auto-numbered (Namibia-style) -------------------------------

.extract_auto_numbered <- function(para_df, num_id, section_prefix, verbose) {
  if (is.null(num_id)) {
    rec_in_lists <- para_df |> filter(is_rec, !is.na(nid))
    if (nrow(rec_in_lists) == 0L) {
      stop("auto-numbered mode forced, but no rec-shaped paragraphs are in ",
           "any numbered list. Try mode = \"literal-prefix\".")
    }
    nid_counts <- sort(table(rec_in_lists$nid), decreasing = TRUE)
    num_id <- names(nid_counts)[1L]
    if (verbose) {
      cat(sprintf("Auto-detected numId='%s' (%d rec-shaped paragraphs)\n",
                  num_id, nid_counts[[1L]]))
      if (length(nid_counts) > 1L) {
        runners <- paste(sprintf("%s (%d)", names(nid_counts)[-1L],
                                 as.integer(nid_counts)[-1L]),
                         collapse = ", ")
        cat(sprintf("Other numIds with rec-shaped paragraphs: %s\n", runners))
      }
    }
  }
  
  numbered <- para_df |> filter(is_rec, !is.na(nid), nid == num_id) |>
    arrange(idx) |>
    mutate(paragraph = sprintf("%s.%d", section_prefix, row_number()))
  unnumbered <- para_df |> filter(is_rec, is.na(nid) | nid != num_id) |>
    arrange(idx) |>
    mutate(paragraph = sprintf("%s.U%d", section_prefix, row_number()))
  
  if (verbose && nrow(unnumbered) > 0L) {
    cat(sprintf(
      "\nWARNING: %d rec-shaped paragraph(s) NOT in numId='%s'. ",
      nrow(unnumbered), num_id))
    cat(sprintf("Labelled %s.U1..%s.U%d:\n",
                section_prefix, section_prefix, nrow(unnumbered)))
    for (i in seq_len(nrow(unnumbered))) {
      cat(sprintf("  [%s | doc-paragraph idx=%d, numId=%s]\n",
                  unnumbered$paragraph[i], unnumbered$idx[i],
                  unnumbered$nid[i] %||% "<none>"))
      cat(sprintf("    %s\n", str_trunc(unnumbered$text[i], 160)))
    }
  }
  in_list_not_rec <- para_df |> filter(!is.na(nid), nid == num_id, !is_rec)
  if (verbose && nrow(in_list_not_rec) > 0L) {
    cat(sprintf(
      "\nWARNING: %d paragraph(s) in numId='%s' do NOT match rec shape:\n",
      nrow(in_list_not_rec), num_id))
    for (i in seq_len(nrow(in_list_not_rec))) {
      cat(sprintf("  [doc-paragraph idx=%d]: %s\n",
                  in_list_not_rec$idx[i],
                  str_trunc(in_list_not_rec$text[i], 160)))
    }
  }
  
  combined <- bind_rows(numbered, unnumbered) |> arrange(idx)
  parsed   <- lapply(combined$text, parse_recommendation)
  tibble(
    paragraph      = combined$paragraph,
    recommendation = vapply(parsed, `[[`, character(1), "text"),
    states         = vapply(parsed, `[[`, character(1), "states")
  )
}

# ---- Format B: literal-prefix (Niger-style) --------------------------------

.extract_literal_prefix <- function(para_df, rec_paras,
                                    section_prefix, verbose) {
  prefixed <- rec_paras |> filter(has_prefix) |>
    mutate(
      sec = str_match(text, .PREFIX_RE)[, 2L],
      num = as.integer(str_match(text, .PREFIX_RE)[, 3L]),
      # Recommendation text with the "X.Y\t" prefix stripped:
      body = str_trim(str_replace(text, .PREFIX_RE, ""))
    ) |>
    arrange(idx)
  
  if (is.null(section_prefix)) {
    section_prefix <- names(sort(table(prefixed$sec), decreasing = TRUE))[1L]
    if (verbose && dplyr::n_distinct(prefixed$sec) > 1L) {
      cat(sprintf(
        "WARNING: literal prefixes use %d different section numbers (%s); ",
        dplyr::n_distinct(prefixed$sec),
        paste(unique(prefixed$sec), collapse = ", ")))
      cat(sprintf("using '%s' (most common).\n", section_prefix))
    }
  }
  
  # Sanity checks on the literal numbering
  if (verbose) {
    nums      <- sort(prefixed$num)
    expected  <- seq_len(max(nums))
    gaps      <- setdiff(expected, nums)
    dup_count <- sum(duplicated(prefixed$num))
    cat(sprintf("Literal prefixes span %s.%d to %s.%d (%d paragraphs).\n",
                section_prefix, min(nums),
                section_prefix, max(nums),
                nrow(prefixed)))
    if (length(gaps) > 0L) {
      cat(sprintf("WARNING: %d gap(s) in numbering: %s%s\n",
                  length(gaps),
                  paste(head(gaps, 10), collapse = ", "),
                  if (length(gaps) > 10L) ", ..." else ""))
    }
    if (dup_count > 0L) {
      cat(sprintf("WARNING: %d duplicate paragraph number(s).\n", dup_count))
    }
  }
  
  # Anything rec-shaped without a literal prefix? (shouldn't happen in Niger,
  # but worth flagging if it does)
  unprefixed <- rec_paras |> filter(!has_prefix)
  if (verbose && nrow(unprefixed) > 0L) {
    cat(sprintf(
      "\nWARNING: %d rec-shaped paragraph(s) lack a literal '%s.N' prefix:\n",
      nrow(unprefixed), section_prefix))
    for (i in seq_len(nrow(unprefixed))) {
      cat(sprintf("  [doc-paragraph idx=%d]: %s\n",
                  unprefixed$idx[i],
                  str_trunc(unprefixed$text[i], 160)))
    }
  }
  
  parsed <- lapply(prefixed$body, parse_recommendation)
  tibble(
    paragraph      = sprintf("%s.%d", prefixed$sec, prefixed$num),
    recommendation = vapply(parsed, `[[`, character(1), "text"),
    states         = vapply(parsed, `[[`, character(1), "states")
  )
}

# ---- Run --------------------------------------------------------------------

if (sys.nframe() == 0) {
  for (path in c(
                 here("data", "UPR_WG_docs", "Mozambique - Draft report circulated on 7 May 2026_amended.docx"))) {
    if (!file.exists(path)) next
    cat("\n----", path, "----\n")
    recs <- extract_upr_recommendations(path)
    print(head(recs, 3))
    print(tail(recs, 2))
  }
}
saveRDS(recs, here("data", "UPR_WG_docs", "Mozambique_upr_recommendations.rds"))
